language: node_js
node_js: 6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
services:
  - mongodb
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
