language: node_js
dist: trusty
sudo: false
node_js: 6
services:
  - mongodb
cache:
  directories:
    - node_modules
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
