language: node_js
node_js:
  - 6
services:
  - mongodb
before_script:
  - npm install
after_success:
  - istanbul cover _mocha -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
