language: node_js
node_js:
  - 6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - mongodb
before_script:
  - npm install
after_success:
  - istanbul cover _mocha -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
